### ISSUE TITLE
Element listed twice in the "Included Mods" section

### ISSUE THREAD

**Issue by guefra** [BurningButter/create-farmersdelight#1]
Hey there!

I really like your modpack, as it's the biggest inspiration for my own private modpack for my server.
When I looked through your _**Included Mods > Libraries, APIs, and other stuff**_ section on your modrinth page I noticed that the mod **_YetAnotherConfigLib_** is listed twice.

Anyways that's all I can "complain". Thank you for your work!

**Comment by BurningButter** [comment]
I really appreciate you reaching out, I've just fixed the issue.
I am really glad that I was able to provide inspiration, this is my first pack and I didn't even expect it to really get any traction.
